language: node_js
os:
  - linux
dist: focal
node_js:
  - "node"
branches:
  only:
    - main
script: skip
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - npm i -g pnpm
install:
  - pnpm i --frozen-lockfile
  - pnpm run build
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/
  fqdn: tour.ntut.club
  strategy: git
  on:
    branch: main
